In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [8]:
#Transformar o arquivo em uma variável
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-06-04 19:28:49.653561
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-06-04 19:28:49.653561
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-06-04 19:28:49.653561

In [9]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_z0019 (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP)
            """)

In [10]:
#Fazer a ingestão do conteúdo na tabela criada
con.execute("INSERT INTO bronze_z0019 SELECT * FROM df")

In [11]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-06-04 19:27:36.581917
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-06-04 19:27:36.581917
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-06-04 19:27:36.581917
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-06-04 19:28:49.653561
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-06-04 19:28:49.653561
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-06-04 19:28:49.653561

In [12]:
con.close()